import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import type { Star } from "@proj/shared";
import { Dialog } from "@base-ui-components/react/dialog";
import { useState } from "react";
import { api, unwrap } from "./lib/api";
import Legend from "./components/Legend";

export default function App() {
  const client = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [modal, setModal] = useState<"blueshift" | "star" | null>(null);
  const blueshifts = useQuery({ queryKey: ["blueshifts"], queryFn: async () => unwrap(await api.api.blueshifts.$get()) });
  const selected = blueshifts.data?.find((item) => item.id === selectedId);
  const stars = useQuery({ queryKey: ["stars", selectedId], enabled: !!selectedId, queryFn: async () => unwrap(await api.api.blueshifts[":id"].stars.$get({ param: { id: selectedId! } })) });
  const northStars = useQuery({ queryKey: ["north-stars"], queryFn: async () => unwrap(await api.api["north-stars"].$get()) });
  const refresh = () => { client.invalidateQueries({ queryKey: ["blueshifts"] }); client.invalidateQueries({ queryKey: ["stars"] }); client.invalidateQueries({ queryKey: ["north-stars"] }); };
  const createBlueshift = useMutation({ mutationFn: async (input: { name: string; goal?: string }) => unwrap(await api.api.blueshifts.$post({ json: input })), onSuccess: (item) => { setSelectedId(item.id); setModal(null); refresh(); } });
  const createStar = useMutation({ mutationFn: async (title: string) => unwrap(await api.api.blueshifts[":id"].stars.$post({ param: { id: selectedId! }, json: { title } })), onSuccess: () => { setModal(null); refresh(); } });
  const updateStar = useMutation({ mutationFn: async ({ id, ...input }: { id: string; completed?: boolean; northStar?: boolean }) => unwrap(await api.api.stars[":id"].$patch({ param: { id }, json: input })), onSuccess: refresh });
  const deleteStar = useMutation({ mutationFn: async (id: string) => unwrap(await api.api.stars[":id"].$delete({ param: { id } })), onSuccess: refresh });
  const deleteBlueshift = useMutation({ mutationFn: async (id: string) => unwrap(await api.api.blueshifts[":id"].$delete({ param: { id } })), onSuccess: (_data, id) => { if (id === selectedId) setSelectedId(null); refresh(); } });

  const queryError = blueshifts.error ?? northStars.error ?? stars.error;
  const starChangeError = updateStar.error ?? deleteStar.error;

  return <main className="min-h-screen bg-surface text-ink"><div className="mx-auto max-w-6xl px-5 py-8 sm:px-10 sm:py-12">
    <header className="mb-10 flex items-end justify-between gap-4"><div><p className="mb-2 font-mono text-xs uppercase tracking-[0.2em] text-accent">Polaris / local command center</p><h1 className="font-display text-5xl font-bold tracking-tight sm:text-7xl">Find your way.</h1><p className="mt-4 text-muted">Big direction. Next useful move.</p></div><button onClick={() => setModal("blueshift")} className="rounded-xl bg-accent px-4 py-3 text-sm font-bold text-white hover:bg-accent/90">+ New Blueshift</button></header>
    {queryError && <section role="alert" className="mb-8 rounded-3xl border border-accent bg-accent/10 p-5"><p className="font-bold">Couldn't load your workspace.</p><p className="mt-1 text-sm">{queryError.message}</p><p className="mt-2 text-sm text-muted">If the API isn't running, start it locally with <code className="font-mono">bun run dev</code> (API on http://localhost:3000).</p></section>}
    {!queryError && (blueshifts.isPending || northStars.isPending) && <p role="status" className="mb-8 text-muted">Loading…</p>}
     <Legend />
    <section aria-labelledby="north-stars-heading" className="mb-8 rounded-3xl bg-ink p-5 text-paper shadow-xl sm:p-7"><div className="mb-5 flex items-center justify-between"><h2 id="north-stars-heading" className="font-display text-2xl font-bold">North Stars</h2><span className="font-mono text-xs text-paper/60">{northStars.isError ? "—" : northStars.data?.length ?? 0} in focus</span></div>{starChangeError && <p role="alert" className="mb-4 rounded-xl bg-accent/20 p-3 text-sm text-paper">Couldn't save a Star: {starChangeError.message}</p>}<div className="grid gap-3 sm:grid-cols-2">{northStars.data?.map((star) => <StarRow key={star.id} star={star} onSelect={() => setSelectedId(star.blueshiftId)} onToggle={(completed) => updateStar.mutate({ id: star.id, completed })} onDelete={() => deleteStar.mutate(star.id)} dark />)}</div></section>
     <div className="grid gap-6 lg:grid-cols-[18rem_1fr]"><aside className="rounded-3xl border border-line bg-paper p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-xl font-bold">Blueshifts</h2><span className="font-mono text-xs text-muted">{blueshifts.isError ? "—" : blueshifts.data?.length ?? 0}</span></div><div className="space-y-2">{blueshifts.data?.map((item) => <div key={item.id} className={`group flex items-start gap-2 rounded-2xl p-3 ${selectedId === item.id ? "bg-accent/10 text-accent" : "hover:bg-surface"}`}><button className="min-w-0 flex-1 text-left" onClick={() => setSelectedId(item.id)}><strong className="block truncate">{item.name}</strong>{item.goal && <span className="mt-1 block truncate text-xs text-muted">{item.goal}</span>}</button><button aria-label={`Delete ${item.name}`} title="Delete Blueshift" onClick={() => deleteBlueshift.mutate(item.id)} className="px-1 text-muted opacity-60 hover:text-accent"><TrashIcon /></button></div>)}</div>{deleteBlueshift.isError && <p role="alert" className="mt-4 rounded-xl bg-accent/10 p-3 text-sm text-accent">Couldn't delete the Blueshift: {deleteBlueshift.error?.message}</p>}</aside>
       <section className="rounded-3xl border border-line bg-paper p-5 sm:p-7">{selected ? <><div className="mb-7 flex items-start justify-between gap-3"><div><p className="font-mono text-xs uppercase tracking-widest text-accent">Selected Blueshift</p><h2 className="mt-1 font-display text-3xl font-bold">{selected.name}</h2>{selected.goal && <p className="mt-2 max-w-xl text-muted">{selected.goal}</p>}</div><button onClick={() => setModal("star")} className="rounded-xl bg-ink px-4 py-3 text-sm font-bold text-paper hover:bg-ink/90">+ New Star</button></div>{starChangeError && <p role="alert" className="mb-4 rounded-xl bg-accent/10 p-3 text-sm text-accent">Couldn't save a Star: {starChangeError.message}</p>}<div className="space-y-3">{stars.data?.map((star) => <StarRow key={star.id} star={star} onToggle={(completed) => updateStar.mutate({ id: star.id, completed })} onNorthStar={(northStar) => updateStar.mutate({ id: star.id, northStar })} onDelete={() => deleteStar.mutate(star.id)} />)}</div></> : <div className="flex min-h-64 items-center justify-center" aria-label="No Blueshift selected"><button disabled className="rounded-xl bg-ink px-4 py-3 text-sm font-bold text-paper opacity-40">+ New Star</button></div>}</section></div>
    {modal === "blueshift" && <BlueshiftModal error={createBlueshift.error?.message} onClose={() => setModal(null)} onSubmit={(input) => createBlueshift.mutate(input)} />}{modal === "star" && selected && <StarModal blueshift={selected.name} error={createStar.error?.message} onClose={() => setModal(null)} onSubmit={(title) => createStar.mutate(title)} />}
  </div></main>;
}

function StarRow({ star, onToggle, onNorthStar, onSelect, onDelete, dark = false }: { star: Star; onToggle: (value: boolean) => void; onNorthStar?: (value: boolean) => void; onSelect?: () => void; onDelete: () => void; dark?: boolean }) {
  return <div className={`flex items-center gap-3 rounded-2xl border p-3 ${dark ? "border-paper/15 bg-paper/10" : "border-line"}`}><input aria-label={`Complete ${star.title}`} type="checkbox" checked={star.completed} onChange={(event) => onToggle(event.target.checked)} className="size-5 accent-accent" />{onSelect ? <button onClick={onSelect} className={`min-w-0 flex-1 text-left ${star.completed ? "text-muted line-through" : ""}`}><span className="block truncate">{star.title}</span>{dark && <span className="mt-1 block font-mono text-[10px] uppercase tracking-wider text-paper/50">North Star</span>}</button> : <span className={`min-w-0 flex-1 ${star.completed ? "text-muted line-through" : ""}`}><span className="block truncate">{star.title}</span></span>}{onNorthStar && <button aria-label={star.northStar ? `Remove ${star.title} as North Star` : `Make ${star.title} a North Star`} onClick={() => onNorthStar(!star.northStar)} className={`text-xl ${star.northStar ? "text-accent" : "text-muted"}`}>★</button>}<button aria-label={`Delete ${star.title}`} title="Delete Star" onClick={onDelete} className="px-1 text-muted hover:text-accent"><TrashIcon /></button></div>;
}

function BlueshiftModal({ error, onClose, onSubmit }: { error?: string; onClose: () => void; onSubmit: (input: { name: string; goal?: string }) => void }) { const [name, setName] = useState(""); const [goal, setGoal] = useState(""); return <Modal title="New Blueshift" onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); if (name.trim()) onSubmit({ name, goal }); }}>{error && <p role="alert" className="mb-4 rounded-xl bg-accent/10 p-3 text-sm text-accent">Couldn't create the Blueshift: {error}</p>}<label className="block text-sm font-bold">Name<input autoFocus value={name} onChange={(e) => setName(e.target.value)} className="mt-2 w-full rounded-xl border border-line bg-surface p-3" /></label><label className="mt-4 block text-sm font-bold">Goal <span className="font-normal text-muted">(optional)</span><textarea value={goal} onChange={(e) => setGoal(e.target.value)} className="mt-2 w-full rounded-xl border border-line bg-surface p-3" rows={3} /></label><Actions disabled={!name.trim()} onClose={onClose} /></form></Modal>; }
function StarModal({ blueshift, error, onClose, onSubmit }: { blueshift: string; error?: string; onClose: () => void; onSubmit: (title: string) => void }) { const [title, setTitle] = useState(""); return <Modal title="New Star" onClose={onClose}><form onSubmit={(event) => { event.preventDefault(); if (title.trim()) onSubmit(title); }}>{error && <p role="alert" className="mb-4 rounded-xl bg-accent/10 p-3 text-sm text-accent">Couldn't create the Star: {error}</p>}<p className="mb-4 rounded-xl bg-surface p-3 text-sm">Blueshift: <strong>{blueshift}</strong></p><label className="block text-sm font-bold">Title<input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} className="mt-2 w-full rounded-xl border border-line bg-surface p-3" /></label><Actions disabled={!title.trim()} onClose={onClose} /></form></Modal>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <Dialog.Root open onOpenChange={(open) => !open && onClose()}><Dialog.Portal><Dialog.Backdrop className="fixed inset-0 z-10 bg-ink/40" /><Dialog.Popup className="fixed left-1/2 top-1/2 z-20 w-[min(90vw,28rem)] -translate-x-1/2 -translate-y-1/2 rounded-3xl bg-paper p-6 shadow-2xl"><div className="mb-5 flex justify-between"><Dialog.Title className="font-display text-2xl font-bold">{title}</Dialog.Title><Dialog.Close aria-label="Close" className="text-2xl text-muted">×</Dialog.Close></div>{children}</Dialog.Popup></Dialog.Portal></Dialog.Root>; }
function Actions({ disabled, onClose }: { disabled: boolean; onClose: () => void }) { return <div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2 text-sm font-bold text-muted">Cancel</button><button disabled={disabled} className="rounded-xl bg-accent px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Create</button></div>; }

function TrashIcon() { return <svg aria-hidden="true" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 6h18" /><path d="M8 6V4h8v2" /><path d="M19 6l-1 14H6L5 6" /><path d="M10 11v5M14 11v5" /></svg>; }
